### PR TITLE
task: create login page

### PR DESCRIPTION
**Pull request by Sufferal**
This PR introduces the sign up for for users. It has error checking for email and password, but stronger validators are needed to ensure security.

### CODE REVIEW

**Review by lavanda888boy — COMMENTED** [review]
Actually I have nothing to suggest, the auth page works fine and the branch can be merged

**Review by lavanda888boy — COMMENTED** [review]
Is it the right place to put the fonts in binary format or there is no other possibility?

**Comment by Sufferal** [comment]
> Is it the right place to put the fonts in binary format or there is no other possibility?

It's faster to have them locally than to import them through a `CDN` (online).

**Review by lavanda888boy — APPROVED** [review]
Ok, then you can merge the branch

**Pull request merged**
